
spring:
  # ???????
  datasource:
    url: jdbc:mysql://localhost:3306/typeman?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    # ???
    type: com.alibaba.druid.pool.DruidDataSource
    # 连接池配置
    druid:
      max-active: 10 # 最大活跃数量 默认8
      min-idle:  2 # 最小空闲数 默认0
      initial-size: 5 # 初始连接数
      max-wait: 2000 # 获取连接最大等待时间 默认 -1
      validation-query: select 1
      validation-query-timeout: 5000
      time-between-eviction-runs-millis: 2000 # 间隔多久进行检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 600000 # 配置连接在池中最小生存的时间
      max-wait-thread-count: 20 # 最大等待线程数
  freemarker:
    check-template-location: false
  thymeleaf:
    cache: false
    mode: HTML
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
# mybatis??
mybatis:
  check-config-location: true
  #  mybatis
  config-location: "classpath:mybatis/mybatis-config.xml"
  #  mapperp配置
  mapper-locations: "classpath:mybatis/mapper/*Mapper.xml"
  #  主类
  type-aliases-package: "com.example.LastJia.dao.entity.*"
baidu.test:
  appid: "44282772"
  apiKey: "4ie1GcEm2bWTHugEAACo9G1U"
  secretKey: "Wl2AQhXu8bWVFT4YqloyXOwkuPONojT1"

